import { molecule, onMount } from 'bunshi'
import type { Camera } from 'nebulosa/src/indi.device'
import bus from 'src/shared/bus'
import { type CameraUpdated, DEFAULT_FLAT_WIZARD_EVENT, DEFAULT_FLAT_WIZARD_START, type FlatWizardEvent, type FlatWizardStart } from 'src/shared/types'
import { unsubscribe } from 'src/shared/util'
import { proxy } from 'valtio'
import { subscribeKey } from 'valtio/utils'
import { Api } from '@/shared/api'
import { initProxy } from '@/shared/proxy'
import { storageGet, storageSet } from '@/shared/storage'
import { updateCameraCaptureStartFromCamera } from '../store/camera.store'
import { equipmentStore, type DeviceState } from '../store/equipment.store'
